### ISSUE TITLE
The "back to my app" link returns "not found"

### ISSUE THREAD

**Issue by tpmccallum** [radu-matei/spin-kv-explorer#15]
![Screenshot 2023-04-18 at 11 42 19 am](https://user-images.githubusercontent.com/9831342/232647966-8c3b84bb-bba0-4d3a-bc0f-b65b88d8bb80.png)

Clicking on the back to my app link, returns the following page

![Screenshot 2023-04-18 at 11 42 43 am](https://user-images.githubusercontent.com/9831342/232647983-68b7b3ec-84e7-4ebb-8aba-d292d460449e.png)

**Comment by mikkelhegn** [comment]
This link has been removed in #14
