### ISSUE TITLE
Doesn't support keys with a leading forward slash `/`' for GET

### ISSUE THREAD

**Issue by mikkelhegn** [radu-matei/spin-kv-explorer#21]
To reproduce:

1. Add a key in the explorer with a trailing forward slash `/` - e.g., `/testing`. This operation succeeds
2. Trey and retrieve the value if the key, This will produce an error in the log `ERROR: cannot get key: no such key`, and no value is shown in the explorer

Tested with `0.9.0`

**Comment by mikkelhegn** [comment]
Might also be the case for deleting a key

**Comment by calebschoepp** [comment]
After playing around I had issues with a `/` anywhere in the key for both get and delete.
