### ISSUE TITLE
Opening an empty store results in an error.

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [radu-matei/spin-kv-explorer#37]
If I setup the key value explorer and attempt to load an empty store it outputs the error message:
```
kv-explorer/:320 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'sort')
    at kv-explorer/:320:16
```

https://discordapp.com/channels/926888690310053918/950022897160839248/1268721853879418970

**Comment by itowlson** [comment]
@kate-goldenring Is this some quirk of the (old) JS SDK perhaps?  Do you have bandwidth to take a look?  If not, I can dig in.

**Comment by kate-goldenring** [comment]
Thank you for filing this issue @JonathanWoollett-Light. In the static frontend of the application we were not appropriately detecting empty stores before sorting the values to display alphabetically, hence the null reference. I've filed a PR with the fix

**Comment by kate-goldenring** [comment]
@karthik2804 do you know of any other changes we may want to get into the KV explorer? Otherwise, we should look at cutting a release with this fix

**Comment by karthik2804** [comment]
@kate-goldenring I can't recall anything off the top of my head. I think we should cut a release.
